from pathlib import Path

path = Path("web_main.py")
text = path.read_text(encoding="utf-8")
if "AUTO_ALIGN_EXPORT_PARITY_V2" in text:
    raise SystemExit(0)

old = '''def _build_resume_full_html(preview_html: str) -> str:\n    """Wrap the preview inner HTML in a standalone document with the project CSS."""\n    css_text = _CSS_PATH.read_text(encoding="utf-8") if _CSS_PATH.exists() else ""\n    filtered = _filter_resume_paper_css(css_text)\n    return (\n        "<!DOCTYPE html><html><head><meta charset=\\"utf-8\\">"\n        "<style>"\n        "* { margin: 0; padding: 0; box-sizing: border-box; }\\n"\n        f"{filtered}\\n"\n        "</style>"\n        "</head><body>"\n        f"<div class=\\"resume-paper\\">{preview_html}</div>"\n        "</body></html>"\n    )\n'''
new = '''# AUTO_ALIGN_EXPORT_PARITY_V2\ndef _build_resume_full_html(\n    preview_html: str,\n    export_css: str = "",\n    auto_align: dict[str, Any] | None = None,\n) -> str:\n    """Wrap preview HTML in a standalone document using the live export CSS/layout."""\n    css_text = _CSS_PATH.read_text(encoding="utf-8") if _CSS_PATH.exists() else ""\n    filtered = _filter_resume_paper_css(css_text)\n    layout_css = ""\n    if isinstance(auto_align, dict):\n        try:\n            font_pt = float(auto_align.get("fontPt", 10))\n            margin_mm = float(auto_align.get("marginMm", 18))\n            h_margin_mm = float(auto_align.get("horizontalMarginMm", 22))\n            density = str(auto_align.get("density", "normal"))\n            line_height = {"compact": 1.20, "normal": 1.30, "spacious": 1.40}.get(density, 1.30)\n            section_scale = {"compact": .82, "normal": 1.00, "spacious": 1.12}.get(density, 1.00)\n            paragraph_scale = {"compact": .78, "normal": 1.00, "spacious": 1.12}.get(density, 1.00)\n            layout_css = (\n                f".resume-paper.auto-aligned {{ box-sizing:border-box; width:210mm; "\n                f"min-height:297mm; padding:{margin_mm}mm {h_margin_mm}mm; "\n                f"font-size:{font_pt}pt; line-height:{line_height}; background:#fff; }}\\n"\n                f".resume-paper.auto-aligned .resume-summary, .resume-paper.auto-aligned .resume-item-sub {{ "\n                f"font-size:10pt; line-height:{line_height}; }}\\n"\n                f".resume-paper.auto-aligned ul {{ font-size:9.5pt; line-height:{line_height}; "\n                f"margin-top:{5 * paragraph_scale}px; margin-bottom:{3 * paragraph_scale}px; }}\\n"\n                f".resume-paper.auto-aligned .resume-section {{ margin-top:{19 * section_scale}px; }}\\n"\n                f".resume-paper.auto-aligned .resume-section h2 {{ margin-bottom:{8 * section_scale}px; }}\\n"\n            )\n        except (TypeError, ValueError):\n            layout_css = ""\n    return (\n        "<!DOCTYPE html><html><head><meta charset=\\"utf-8\\">"\n        "<style>"\n        "* { margin: 0; padding: 0; box-sizing: border-box; }\\n"\n        f"{filtered}\\n{export_css}\\n{layout_css}"\n        "</style>"\n        "</head><body>"\n        f"<div class=\\"resume-paper\\">{preview_html}</div>"\n        "</body></html>"\n    )\n'''
if old not in text:
    raise SystemExit("Could not find _build_resume_full_html block")
text = text.replace(old, new, 1)

old_route = '''    if file_format == "docx" and body.get("state"):\n        return await _export_docx_from_state(body["state"], stem)\n\n    if not html_content:\n        raise HTTPException(status_code=400, detail="No HTML content")\n\n    full_html = _build_resume_full_html(html_content)\n\n    if file_format == "pdf":\n        return await _export_pdf_playwright(full_html, stem)\n    else:\n        return await _export_docx_playwright(full_html, stem)\n'''
new_route = '''    # Prefer the live preview HTML whenever supplied. The legacy structured-state\n    # DOCX exporter is only a fallback for callers that do not send HTML.\n    if not html_content:\n        if file_format == "docx" and body.get("state"):\n            return await _export_docx_from_state(body["state"], stem)\n        raise HTTPException(status_code=400, detail="No HTML content")\n\n    full_html = _build_resume_full_html(\n        html_content,\n        str(body.get("css", "") or ""),\n        body.get("autoAlign") if isinstance(body.get("autoAlign"), dict) else None,\n    )\n\n    if file_format == "pdf":\n        return await _export_pdf_playwright(full_html, stem)\n    return await _export_docx_playwright(\n        full_html,\n        stem,\n        body.get("autoAlign") if isinstance(body.get("autoAlign"), dict) else None,\n    )\n'''
if old_route not in text:
    raise SystemExit("Could not find builder_export block")
text = text.replace(old_route, new_route, 1)

text = text.replace(
'''async def _export_docx_playwright(full_html: str, stem: str) -> Response:\n''',
'''async def _export_docx_playwright(\n    full_html: str,\n    stem: str,\n    auto_align: dict[str, Any] | None = None,\n) -> Response:\n''',
1,
)

old_docx = '''    doc = Document()\n    sec = doc.sections[0]\n    sec.page_width = Mm(210)\n    sec.page_height = Mm(297)\n    sec.top_margin = Mm(18)\n    sec.bottom_margin = Mm(18)\n    sec.left_margin = Mm(22)\n    sec.right_margin = Mm(22)\n\n    normal = doc.styles["Normal"]\n    normal.font.name = "Arial"\n    normal.font.size = Pt(10)\n    normal.font.color.rgb = RGBColor(0x18, 0x21, 0x33)\n    normal.paragraph_format.space_after = Pt(2)\n    normal.paragraph_format.space_before = Pt(0)\n'''
new_docx = '''    layout = auto_align if isinstance(auto_align, dict) else {}\n    try:\n        body_pt = float(layout.get("fontPt", 10))\n        margin_mm = float(layout.get("marginMm", 18))\n        h_margin_mm = float(layout.get("horizontalMarginMm", 22))\n    except (TypeError, ValueError):\n        body_pt, margin_mm, h_margin_mm = 10.0, 18.0, 22.0\n    density = str(layout.get("density", "normal"))\n    line_height = {"compact": 1.20, "normal": 1.30, "spacious": 1.40}.get(density, 1.30)\n    section_scale = {"compact": .82, "normal": 1.00, "spacious": 1.12}.get(density, 1.00)\n    paragraph_scale = {"compact": .78, "normal": 1.00, "spacious": 1.12}.get(density, 1.00)\n\n    doc = Document()\n    sec = doc.sections[0]\n    sec.page_width = Mm(210)\n    sec.page_height = Mm(297)\n    sec.top_margin = Mm(margin_mm)\n    sec.bottom_margin = Mm(margin_mm)\n    sec.left_margin = Mm(h_margin_mm)\n    sec.right_margin = Mm(h_margin_mm)\n\n    normal = doc.styles["Normal"]\n    normal.font.name = "Arial"\n    normal.font.size = Pt(body_pt)\n    normal.font.color.rgb = RGBColor(0x18, 0x21, 0x33)\n    normal.paragraph_format.space_after = Pt(2 * paragraph_scale)\n    normal.paragraph_format.space_before = Pt(0)\n    normal.paragraph_format.line_spacing = line_height\n'''
if old_docx not in text:
    raise SystemExit("Could not find DOCX layout block")
text = text.replace(old_docx, new_docx, 1)

text = text.replace('''                run.font.size = Pt(9.5)\n''', '''                run.font.size = Pt(max(9.0, body_pt - 0.5))\n''', 1)
text = text.replace('''            p.paragraph_format.space_before = Pt(12)\n            p.paragraph_format.space_after = Pt(4)\n''', '''            p.paragraph_format.space_before = Pt(12 * section_scale)\n            p.paragraph_format.space_after = Pt(4 * section_scale)\n            p.paragraph_format.line_spacing = line_height\n''', 1)
text = text.replace('''        if is_bold:\n            run.font.size = Pt(10.5)\n''', '''        if is_bold:\n            run.font.size = Pt(body_pt + 0.5)\n''', 1)
text = text.replace('''            run.font.size = Pt(10)\n            run.font.color.rgb = RGBColor(0x33, 0x33, 0x33)\n\n        p.paragraph_format.space_before = Pt(1)\n        p.paragraph_format.space_after = Pt(1)\n''', '''            run.font.size = Pt(body_pt)\n            run.font.color.rgb = RGBColor(0x33, 0x33, 0x33)\n\n        p.paragraph_format.space_before = Pt(1 * paragraph_scale)\n        p.paragraph_format.space_after = Pt(1 * paragraph_scale)\n        p.paragraph_format.line_spacing = line_height\n''', 1)

path.write_text(text, encoding="utf-8")
print("patched")
